<footer class="container">
    <a href="/" class="logo-link">
        <img src="/assets/img/logo.svg" alt="Food Delivery">
        <span>Delivery Food</span>
    </a>
    <nav class="menu"></nav>
    <div class="socials">
        <a href="#" target="_blank" title="Instagram">
            <img src="/assets/img/insta.svg" alt="Instagram">
        </a>
        <a href="#" target="_blank" title="Facebook">
            <img src="/assets/img/fb.svg" alt="Facebook">
        </a>
        <a href="#" target="_blank" title="VK">
            <img src="/assets/img/vk.svg" alt="VK">
        </a>
    </div>
</footer>
