<header class="container">
    <a href="/" class="logo-link">
        <img src="/assets/img/logo.svg" alt="Food Delivery">
        <span>Delivery Food</span>
    </a>
    <form method="post" class="search">
        <label id="address-label">
            <input id="address-input" placeholder="Адрес доставки">
        </label>
    </form>
    <div class="user">
        <a href="#" id="login" class="btn btn-primary">
            <img src="/assets/img/user.svg" alt="">
            <span class="btn-text">Войти</span>
        </a>
        <a href="/cart" id="login" class="btn btn-default">
            <img src="/assets/img/cart.svg" alt="">
            <span class="btn-text">Корзина</span>
        </a>
    </div>
</header>
