<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Food Delivery</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/app.css?<?= filemtime(__DIR__ . '/assets/css/app.css') ?>">
</head>
<body>
<header class="container">
    <a href="/" class="logo-link">
        <img src="assets/img/logo.svg" alt="Food Delivery">
        <span>Delivery Food</span>
    </a>
    <div class="search"></div>
    <div class="user"></div>
</header>
<main>
    <div class="container slider">
        <div class="promo">
            <img src="assets/img/promo1.png" alt="Promo 1">
        </div>
    </div>
</main>
<footer class="container">
    <a href="/" class="logo-link">
        <img src="assets/img/logo.svg" alt="Food Delivery">
        <span>Delivery Food</span>
    </a>
    <nav class="menu"></nav>
    <div class="socials">
        <a href="#" target="_blank" title="Instagram">
            <img src="assets/img/insta.svg" alt="Instagram">
        </a>
        <a href="#" target="_blank" title="Facebook">
            <img src="assets/img/fb.svg" alt="Facebook">
        </a>
        <a href="#" target="_blank" title="VK">
            <img src="assets/img/vk.svg" alt="VK">
        </a>
    </div>
</footer>
<script src="assets/js/app.js?<?= filemtime(__DIR__ . '/assets/js/app.js') ?>"></script>
</body>
</html>
